name: Copilot Setup - Preinstall Tools and Warm Caches

on:
  workflow_dispatch: # Can be triggered manually
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM UTC to keep caches warm

jobs:
  copilot-setup-steps:  # <-- must be this exact key
    runs-on: ubuntu-latest
    name: Setup Tools and Warm Caches
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Verify preinstalled Node.js version
        run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Using preinstalled Node.js for faster GitHub agent startup"

      - name: Setup npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Enable Corepack for consistent package managers
        run: |
          corepack enable
          echo "Corepack enabled - toolchain consistency improved"

      - name: Verify toolchain versions
        run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Corepack version: $(corepack --version)"

      - name: Install dependencies with clean cache
        run: |
          npm ci --prefer-offline --no-audit
          echo "Dependencies installed and cached"

      - name: Warm build cache
        run: |
          echo "Warming build caches..."
          CI=false npm run build
          echo "Build cache warmed successfully"

      - name: Warm test cache
        run: |
          echo "Warming test caches..."
          npm test -- --watchAll=false --passWithNoTests --silent || echo "Test cache warming completed (some test failures ignored)"
          echo "Test cache warmed successfully"

      - name: Cache summary
        run: |
          echo "✅ Using preinstalled Node.js $(node --version) - no installation time!"
          echo "✅ npm dependencies cached" 
          echo "✅ TypeScript build cache warmed"
          echo "✅ Jest test cache warmed"
          echo "✅ Corepack toolchain ready"
          echo ""
          echo "🚀 GitHub agents will start significantly faster!"
